import type { Project } from "@/components/ProjectCard";

export const PROJECTS: Project[] = [
  {
    slug: "ddolbae",
    title: "🤖 AI/LLM-powered Analytics Chatbot",
    oneLiner: "Persona fine-tuning + quantization 기반 self-hosting, 운영비 절감",
    category: "LLM",
    featured: true,
    stack: ["Python", "PyTorch", "Transformers", "QLoRA", "bitsandbytes", "HF Hub", "Gradio"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/jaychatbot_2nd" },
      { label: "Demo", href: "http://www.duboobanmo.site" },
      { label: "Blog", href: "https://velog.io/@jaylaydown/series/side-project-1" },
    ],
  },
  {
    slug: "animal-test",
    title: "🐾 Social Animal Type Test (Metacognition & Situation Reading)",
    oneLiner: "11가지 사회적 동물 유형 테스트: 설계–채점–UI/UX–배포 end-to-end",
    category: "Other",
    featured: true,
    stack: ["Python", "Gradio", "HTML/CSS", "Hugging Face Spaces"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/animal_test" },
      { label: "Demo", href: "https://myanimaltest.site/" },
      { label: "Space", href: "https://huggingface.co/spaces/Jay1121/animal_test" },
      { label: "Blog", href: "https://velog.io/@jaylaydown/%EB%82%98%EB%A7%8C%EC%9D%98-%EC%8B%AC%EB%A6%AC-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-%EB%8F%99%EB%AC%BC-%EC%9C%A0%ED%98%95-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8" },
    ],
  },
  {
    slug: "auto-segment-tool",
    title: "🔧 Auto Segment Tool – Desktop Application (EXE)",
    oneLiner: "데이터 로딩→PCA→결정트리 세그→시각화/Excel 자동 리포트 GUI",
    category: "Segmentation",
    featured: true,
    stack: ["Python", "PySide6", "scikit-learn", "Pandas", "Excel Automation", "PyInstaller"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/auto_segment" },
      { label: "Download", href: "https://drive.google.com/uc?id=1l6dMl6QHx7fJAeh8zL3xPIJX572mtnum&export=download" },
    ],
  },
  {
    slug: "bayesian-dashboard",
    title: "🌐 Bayesian Modeling & Dashboard",
    oneLiner: "계층적 베이지안으로 퍼널 분석 + 대시보드(불확실성 기반 해석)",
    category: "Bayesian",
    featured: true,
    stack: ["Python", "PyMC", "ArviZ", "pandas", "NumPy", "Plotly/Dash"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/bayesian_dashboard" },
      { label: "Dashboard", href: "https://jay1121-bayesian-dashboard.hf.space" },
    ],
  },
  {
    slug: "bayesian-norms",
    title: "📈 Brand Image Evaluation with Bayesian Norms",
    oneLiner: "소셜+설문 결합 & 데이터 증강 기반 브랜드 이미지 평가 대시보드",
    category: "Bayesian",
    stack: ["Python", "pandas", "scikit-learn", "KoNLPy/spaCy", "PyMC", "VBA"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/bayesian_norm" },
      { label: "Blog", href: "https://velog.io/@jaylaydown/BayesianAdjectiveNorm" },
      { label: "Dashboard", href: "https://github.com/jay-lay-down/bayesian_norm/blob/main/assets/bayesian_norm_fin.xlsm" },
    ],
  },
  {
    slug: "demand-forecasting",
    title: "📊 Demand Forecasting",
    oneLiner: "SARIMAX 파이프라인 + R 패키지 개발(MAPE 0.9~7.5%, MASE 0.3~0.8%)",
    category: "Forecasting",
    featured: true,
    stack: ["R", "forecast", "caret", "tseries", "lmtest", "devtools", "usethis", "roxygen2", "testthat"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/demand_forecasting" },
      { label: "Slides", href: "https://github.com/jay-lay-down/demand_forecasting/blob/main/assets/Example_Forecasting%20Projects.pdf" },
    ],
  },
  {
    slug: "brand-share-forecasting",
    title: "☑ Brand Share% Forecasting",
    oneLiner: "Softmax 최적화 + seq2seq LSTM(Additive Attention)로 점유율 시퀀스 예측",
    category: "Forecasting",
    stack: ["Python", "TensorFlow/Keras", "LSTM seq2seq", "Additive Attention", "pandas", "NumPy"],
    links: [{ label: "Repo", href: "https://github.com/jay-lay-down/seq2seq_softmax" }],
  },
  {
    slug: "employee-engagement",
    title: "👥 Drivers of Employee Engagement",
    oneLiner: "LPA로 몰입/이직 패턴 세분화 → 실행 가능한 조직 전략 도출",
    category: "Segmentation",
    stack: ["R", "lavaan", "tidyLPA/mclust"],
    links: [
      { label: "Repo", href: "https://github.com/jay-lay-down/LPA_synthetic_vars" },
      { label: "Slides", href: "https://github.com/jay-lay-down/LPA_synthetic_vars/blob/main/assets/LPA_example.pdf" },
    ],
  },
  {
    slug: "other-projects",
    title: "🔢 Other Projects",
    oneLiner: "소셜마이닝/제안서 등 다양한 프로젝트 슬라이드 모음",
    category: "Other",
    stack: ["Slides"],
    links: [{ label: "Slides", href: "https://github.com/jay-lay-down/jay-lay-down/blob/main/assets/Example_projects.pdf" }],
  },
];
